apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssldemo-dep
  labels:
    app: ssldemo
spec:
  selector:
    matchLabels:
      app: ssldemo
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ssldemo
        version: "0.1"
        aadpodidbinding: berichten-deployment
    spec:
      serviceAccountName: ssldemo-sa
      restartPolicy: Always
      containers:
        - image: k8s.gcr.io/echoserver:1.10
          # - image: mcr.microsoft.com/dotnet/core/samples:aspnetapp
          # - image: r.j3ss.co/party-clippy
          name: ssldemo
          securityContext:
            #runAsUser: 65534 # 1000=root, 65534=nobody
            #runAsGroup: 3000
            #fsGroup: 2000
            #runAsNonRoot: true
            allowPrivilegeEscalation: false
            privileged: false
            #readOnlyRootFilesystem: true
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VSTS_AGENT
              value: $(POD_NAME)-agent
          resources:
            requests:
              cpu: "20m"
              memory: "55M"
            limits:
              cpu: "100m"
              memory: "80M"
          livenessProbe:
            httpGet:
              path: "/"
              port: 8080
            timeoutSeconds: 5
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: "/"
              port: 8080
            timeoutSeconds: 5
            initialDelaySeconds: 60
          ports:
            - containerPort: 8080
              name: http-main
      #     volumeMounts:
      #       - name: kv-secrets
      #         mountPath: /secrets
      #         readOnly: true
      # volumes:
      #   - name: kv-secrets
      #     csi:
      #       driver: secrets-store.csi.k8s.io
      #       readOnly: true
      #       volumeAttributes:
      #         providerName: "azure"
      #         usePodIdentity: "true"
      #         keyvaultName: "kv-teamb-development"
      #         objects:  |
      #           array:
      #             - |
      #               objectName: ServiceBus--AsbConnectionString
      #               objectType: secret        # object types: secret, key or cert
      #             - |
      #               objectName: ServiceBus--DataBusConnectionString
      #               objectType: secret
      #               objectVersion: ""
      #         resourceGroup: ""               # the resource group of the KeyVault
      #         subscriptionId: ""              # the subscription ID of the KeyVault
      #         tenantId: "d8f00f92-64fd-40fe-9f0b-e09e6b0875cc"
      #   - name: kv-secrets
      #     flexVolume:
      #       driver: "azure/kv"
      #       options:
      #         usepodidentity: "true"
      #         keyvaultname: "kv-teamb-development"
      #         keyvaultobjectnames: "ServiceBus--AsbConnectionString;ServiceBus--DataBusConnectionString;BestaatNiet"
      #         keyvaultobjectaliases: "ServiceBus__AsbConnectionString;ServiceBus__DataBusConnectionString;BestaatNietAlias"
      #         keyvaultobjecttypes: "secret;secret;secret"
      #         tenantid: "d8f00f92-64fd-40fe-9f0b-e09e6b0875cc"      
